### ISSUE TITLE
chm file cannot be open when extact path contains special character

### ISSUE THREAD

**Issue by LeoYawoo** [vzhd1701/qt-documentation-chm-autoupdated#1]
when i extact the chm.zip to some folder like e:/dev/Qt-5.15.2.chm/Qt-5.15.2.chm,the chm content cannot shown normal;
then i rename e:/dev/Qt-5.15.2.chm to e:/dev/aaa,everything works.

**Comment by vzhd1701** [comment]
I think it's a Microsoft HTML Help Reader bug. I tested this with other CHM files, and they cannot be opened either. I use ExtraCHM, and it works OK.
